// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqAgFZmqWVCnSjTjJE1IBFjwg6Gecujq4',
    appId: '1:485547942487:android:038c7a8791450d68f23912',
    messagingSenderId: '485547942487',
    projectId: 'tasksheet-firebase',
    storageBucket: 'tasksheet-firebase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlOyza2j8kQdmyNHjhyDcl8WTQrH9Q9q4',
    appId: '1:485547942487:ios:2a96ea3c4dc7e49bf23912',
    messagingSenderId: '485547942487',
    projectId: 'tasksheet-firebase',
    storageBucket: 'tasksheet-firebase.firebasestorage.app',
    iosBundleId: 'com.example.tasksheetFirebase',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAY72WxZ2EiuuLThRtMW1LwzaGk4Od0Wtw',
    appId: '1:485547942487:web:758b5e2ba4a9e125f23912',
    messagingSenderId: '485547942487',
    projectId: 'tasksheet-firebase',
    authDomain: 'tasksheet-firebase.firebaseapp.com',
    storageBucket: 'tasksheet-firebase.firebasestorage.app',
    measurementId: 'G-J8XV1J2M5H',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlOyza2j8kQdmyNHjhyDcl8WTQrH9Q9q4',
    appId: '1:485547942487:ios:2a96ea3c4dc7e49bf23912',
    messagingSenderId: '485547942487',
    projectId: 'tasksheet-firebase',
    storageBucket: 'tasksheet-firebase.firebasestorage.app',
    iosBundleId: 'com.example.tasksheetFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAY72WxZ2EiuuLThRtMW1LwzaGk4Od0Wtw',
    appId: '1:485547942487:web:0db4e2e16ba57e04f23912',
    messagingSenderId: '485547942487',
    projectId: 'tasksheet-firebase',
    authDomain: 'tasksheet-firebase.firebaseapp.com',
    storageBucket: 'tasksheet-firebase.firebasestorage.app',
    measurementId: 'G-DGKX9YERTZ',
  );

}